# Generated by Django 5.1 on 2024-09-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_admin_remove_tbl_districts_district_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_admin',
            new_name='tbl_adminreg',
        ),
    ]
