# Generated by Django 5.1 on 2024-09-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_rename_tbl_admin_tbl_adminreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_districts',
        ),
    ]
