# Generated by Django 5.1 on 2024-09-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_delete_tbl_districts'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districts_name', models.CharField(max_length=50)),
            ],
        ),
    ]
